In [1]:
import pandas as pd

In [11]:
df = pd.read_csv("data/blinkit_customer_feedback.csv")
df

,feedback_id,order_id,customer_id,rating,feedback_text,feedback_category,sentiment,feedback_date
0,2234710,1961864118,30065862,4,"It was okay, nothing special.",Delivery,Neutral,2024-07-17
1,5450964,1549769649,9573071,3,The order was incorrect.,App Experience,Negative,2024-05-28
2,482108,9185164487,45477575,3,"It was okay, nothing special.",App Experience,Neutral,2024-09-23
3,4823104,9644738826,88067569,4,The product met my expectations.,App Experience,Neutral,2023-11-24
4,3537464,5427684290,83298567,3,Product was damaged during delivery.,Delivery,Negative,2023-11-20
...,...,...,...,...,...,...,...,...
4995,9024060,1669690997,62600289,3,Taste was not as expected.,Product Quality,Negative,2023-12-25
4996,4715968,8340761903,53640286,3,"Average experience, could improve.",Product Quality,Neutral,2023-11-27
4997,9621021,5936301790,87059497,4,"Average experience, could improve.",App Experience,Neutral,2024-06-21
4998,1134095,5710579377,67310893,4,"Average experience, could improve.",Delivery,Neutral,2024-06-06
4999,6578433,2494813730,28663279,4,"It was okay, nothing special.",Customer Service,Neutral,2023-08-23

In [14]:
data = pd.DataFrame({'rating': [1, 2, 3, 4, 5]})
data['experience'] = data['rating'].map({1: 'very poor', 2: 'poor', 3: 'average', 4: 'good', 5: 'excellent'})
df

,feedback_id,order_id,customer_id,rating,feedback_text,feedback_category,sentiment,feedback_date
0,2234710,1961864118,30065862,4,"It was okay, nothing special.",Delivery,Neutral,2024-07-17
1,5450964,1549769649,9573071,3,The order was incorrect.,App Experience,Negative,2024-05-28
2,482108,9185164487,45477575,3,"It was okay, nothing special.",App Experience,Neutral,2024-09-23
3,4823104,9644738826,88067569,4,The product met my expectations.,App Experience,Neutral,2023-11-24
4,3537464,5427684290,83298567,3,Product was damaged during delivery.,Delivery,Negative,2023-11-20
...,...,...,...,...,...,...,...,...
4995,9024060,1669690997,62600289,3,Taste was not as expected.,Product Quality,Negative,2023-12-25
4996,4715968,8340761903,53640286,3,"Average experience, could improve.",Product Quality,Neutral,2023-11-27
4997,9621021,5936301790,87059497,4,"Average experience, could improve.",App Experience,Neutral,2024-06-21
4998,1134095,5710579377,67310893,4,"Average experience, could improve.",Delivery,Neutral,2024-06-06
4999,6578433,2494813730,28663279,4,"It was okay, nothing special.",Customer Service,Neutral,2023-08-23

In [5]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Length: 5000, dtype: bool

In [20]:
import pandas as pd

# ðŸ”¹ Step 1: Load your dataset from file path
# Replace 'your_file_path.csv' with your actual path (CSV or Excel)
df = pd.read_csv('data/blinkit_customer_feedback.csv')    # or pd.read_excel('your_file_path.xlsx')

# ðŸ”¹ Step 2: Define the mapping from rating to experience
rating_map = {
    1: "Very Poor",
    2: "Poor",
    3: "Average",
    4: "Good",
    5: "Excellent"
}

# ðŸ”¹ Step 3: Create the new column 'experience' based on 'rating'
df['experience'] = df['rating'].map(rating_map)
# Save the DataFrame to Excel file
df.to_csv("experience.csv", index=False)
df

,feedback_id,order_id,customer_id,rating,feedback_text,feedback_category,sentiment,feedback_date,experience
0,2234710,1961864118,30065862,4,"It was okay, nothing special.",Delivery,Neutral,2024-07-17,Good
1,5450964,1549769649,9573071,3,The order was incorrect.,App Experience,Negative,2024-05-28,Average
2,482108,9185164487,45477575,3,"It was okay, nothing special.",App Experience,Neutral,2024-09-23,Average
3,4823104,9644738826,88067569,4,The product met my expectations.,App Experience,Neutral,2023-11-24,Good
4,3537464,5427684290,83298567,3,Product was damaged during delivery.,Delivery,Negative,2023-11-20,Average
...,...,...,...,...,...,...,...,...,...
4995,9024060,1669690997,62600289,3,Taste was not as expected.,Product Quality,Negative,2023-12-25,Average
4996,4715968,8340761903,53640286,3,"Average experience, could improve.",Product Quality,Neutral,2023-11-27,Average
4997,9621021,5936301790,87059497,4,"Average experience, could improve.",App Experience,Neutral,2024-06-21,Good
4998,1134095,5710579377,67310893,4,"Average experience, could improve.",Delivery,Neutral,2024-06-06,Good
4999,6578433,2494813730,28663279,4,"It was okay, nothing special.",Customer Service,Neutral,2023-08-23,Good